### ISSUE TITLE
Milestone 1 Feedback: minor fixes

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/mds522_305#14]
- [x] Move EDA files into a subdirectory
- [x] Pay attention to communicating through Github issues and writing more distinct commit messages
- [x] Proofreading is required to correct grammar mistakes and typos
